### ISSUE TITLE
Certain parameters leave gaps in hex coverage

### ISSUE THREAD

**Issue by kasarol** [datagovsg/hextile#1]
It seems that specific parameters create a scenario where some of the inner hexagons are not present in the ouput. Please check this piece of code. It should return 29 hexagons, but it returns 27 in a pattern shown in attached image.
![missing_tiles](https://user-images.githubusercontent.com/8488349/29511298-76520344-8667-11e7-80ab-f6aba27cc7b1.png)
 
`var hextile = require("hextile");

var polygonMap = {
  "type": "Polygon",
  "coordinates": [
    [
      [
        24.784687,
        60.241633
      ],
      [
        24.971647,
        60.264457
      ],
      [
        25.001731,
        60.287013
      ],
      [
        25.08537,
        60.271777
      ],
      [
        25.080409,
        60.251259
      ],
      [
        25.138487,
        60.238957
      ],
      [
        25.185759,
        60.284609
      ],
      [
        25.1542,
        60.359349
      ],
      [
        25.07913,
        60.374366
      ],
      [
        25.019999,
        60.369841
      ],
      [
        25.043241,
        60.347713
      ],
      [
        24.956065,
        60.338632
      ],
      [
        24.836719,
        60.397582
      ],
      [
        24.827491,
        60.396888
      ],
      [
        24.749508,
        60.342396
      ],
      [
        24.747487,
        60.323355
      ],
      [
        24.761217,
        60.323158
      ],
      [
        24.77154,
        60.299097
      ],
      [
        24.761206,
        60.267953
      ],
      [
        24.784687,
        60.241633
      ]
    ]
  ]
};

var hexmap = hextile( polygonMap, { 
    shape: 'hexagon',
    width: 5000,
    center: [25.14652292594583,60.284609],
    tilt: 90
});
console.log("Count: " + hexmap.length + ", hexmap: " + JSON.stringify(hexmap) );`

**Comment by yongjun21** [comment]
Let me check

**Comment by kasarol** [comment]
Thank you for the fast fix! 

Off the topic, I would love to have a feature where I could let the library pick the center coordinates of the first hexagon in a way that would result in the least amount of hexagon to cover the polygon.

**Comment by yongjun21** [comment]
Might be useful in certain specialized use cases but I suspect an algorithm to do that is probably not going to be any faster than O(n2) thus not really practical to implement.
